language: php

env:
  global:
    - SETUP=stable

matrix:
  include:
    - php: 7.1
    - php: 7.1
      env: SETUP=lowest
    - php: 7.2
    - php: 7.2
      env: SETUP=lowest
    - php: 7.3
    - php: 7.3
      env: SETUP=lowest
    - php: 7.4snapshot
    - php: 7.4snapshot
      env: SETUP=lowest
  allow_failures:
    - php7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - if [[ $SETUP == 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $SETUP == 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --prefer-lowest --no-suggest; fi

script: vendor/bin/phpunit
