name: Tests (PHP)
on:
  pull_request:
  push:
    branches:
      - main
      - '*.x'

jobs:
  phpunit:
    name: PHP ${{ matrix.php }} (${{ matrix.os }} with ${{ matrix.dependency-version }} deps)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        php: [7.3, 7.4]
        dependency-version: [highest, lowest]

    steps:
      - uses: actions/checkout@v3

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, fileinfo
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependency-version }}
          composer-options: "--prefer-dist"

      - name: Execute tests
        run: vendor/bin/phpunit
